### ISSUE TITLE
v4 release notes

### ISSUE THREAD

**Issue by flipchart** [jonathantneal/precss#126]
I see v4 has been released. Could you explain what has changed, and (since this is a major release) what are the breaking changes?

As a side note, the project doesn't seem to use Github releases (any more). Is there a reason for this? I think for most people it's the first place they go to see what a new version contains

**Comment by jonathantneal** [comment]
I always update the CHANGELOG.md.

https://github.com/jonathantneal/precss/blob/master/CHANGELOG.md

I don’t always remember to copy and paste it into releases.

**Comment by maxmilton** [comment]
Have a look in the change log: https://github.com/jonathantneal/precss/blob/master/CHANGELOG.md

To see the actual code changes you can also compare the difference between the last version, 3.1.2 and this version 4.0.0: https://github.com/jonathantneal/precss/compare/2c813534f7b0a496b9a4fbfa1a646db6b9a038d7...955660433169ff20506b63020ffc902a2f5e6159

> "As a side note, the project doesn't seem to use Github releases (any more). Is there a reason for this? I think for most people it's the first place they go to see what a new version contains"

I normally go straight to the CHANGELOG first because it tends to be a much source of info. Not all projects use only Github.
