### ISSUE TITLE
Calc function and minus don't work together.

### ISSUE THREAD

**Issue by nwind** [jonathantneal/precss#98]
```
$width: 9px;
$outer-width: calc($width + 1px);

.test {
  width: -$outer-width;
}
```

output will be

```
.test {
  width: 10px;
}
```

**Comment by lkraav** [comment]
@nwind try multiplying `-1` instead.

**Comment by jonathantneal** [comment]
Those magic calculations in Sass are not present in PreCSS because they conflict with real emerging syntaxes in CSS. For instance, the dividing symbol `/` can now be used to split certain arguments in [Grid Layout](https://jonathantneal.github.io/css-db/#css-grid). In another instance, the greater than symbol `>` can be used to markup [Media Queries Ranges](https://jonathantneal.github.io/css-db/#mediaqueries-mq-ranges).
